TebLocalPlannerROS:

  #Robot Params
  acc_lim_x: 3.0
  acc_lim_theta: 3.0

  max_vel_x: 0.75
  max_vel_x_backwards: 0.30

  max_vel_y: 0.45
  acc_lim_y: 2.5

  max_vel_theta: 0.50

  min_turning_radius: 0.0

  wheelbase: 0.64

  footprint_model/type: "polygon"
  footprint_model/vertices: [[0.42,0.24],[0.42,-0.24],[-0.55,-0.24],[-0.55,0.24]]

  is_footprint_dynamic: false


  #Goal Tolerance Params
  xy_goal_tolerance: 0.15 #0.02
  yaw_goal_tolerance: 0.35 #0.018

  #Trajectory Configuration Params
  dt_ref: 0.3
  dt_hysteresis: 0.1

  min_samples: 3

  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: -0.1

  max_global_plan_lookahead_dist: 2.0
  force_reinit_new_goal_dist: 1.0

  feasibility_check_no_poses: 4
  publish_feedback: false

  allow_init_with_backwards_motion: true

  exact_arc_length: false
  shrink_horizon_min_duration: 0.0

  #Obstacle Params
  min_obstacle_dist: 0.04
  include_costmap_obstacles: true

  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  inflation_dist: 0.14
  dynamic_obstacle_inflation_dist: 0.14

  include_dynamic_obstacles: true
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 7.0
  obstacle_association_cutoff_factor: 15.0

  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

  #Optimization Params
  no_inner_iterations: 5
  no_outer_iterations: 4

  penalty_epsilon: 0.1

  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0

  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0

  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 100.0 #1.0
  weight_kinematics_turning_radius: 1.0
  weight_optimaltime: 1.0
  weight_obstacle: 55.0
  weight_viapoint: 1.0
  weight_inflation: 0.1
  weight_adapt_factor: 1.75

  weight_shortest_path: 1.5

  #Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0

  selection_viapoint_cost_scale: 1.0
  selection_alternative_time_cost: false

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1

  obstacle_heading_threshold: 1.0
  visualize_hc_graph: false
  viapoints_all_candidates: true
  switching_blocking_period: 0.0

  #Miscellaneous Params
  odom_topic: "world"
  map_frame: "world"